sudo: required
group: travis_lts

env:
  global:
    TERM=dumb

language: java
jdk:
  - openjdk8
  - oraclejdk8

install: true
before_install:
  # install latest docker
  - sudo apt update -y
  - sudo apt install -y docker-ce
  - sudo apt-cache madison docker-ce

  # docker-compose, curl, jq and httpie
  - sudo apt install -y docker python-pip jq curl libxml2-utils
  - sudo pip install docker-compose httpie
  - sudo usermod -aG docker $(whoami)

  - source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)

  # kill whatever ports is running
  - stop_any 5432 5672 27017 8080

script:
  - bash gradlew clean build docs

  - export parent=$(pwd)

  # jboss-eap-h2-ejb, jboss-eap-h2-cdi
  - >
    for path in \
      java-gradle-maven-docker-starter \
    ; do

      cd ${parent}/${path}

      bash mvnw clean package
      bash gradlew clean build
      docker-compose build --force-rm --no-cache --pull
      docker-compose up --force-recreate --remove-orphans
      docker-compose down -v

    done;

  - docker system prune -af --volumes

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
