sudo: required
group: travis_lts
service:
- docker
env:
  global:
    TERM=dumb
language: java
jdk:
- openjdk8
- oraclejdk8
install: true
before_install:
# install latest docker
- sudo apt update -y || true
- sudo apt install -y docker-ce python-pip jq curl libxml2-utils
- sudo pip install docker-compose httpie
- source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
- stop_any 5432 5672 27017 8080
script:
- bash gradlew clean build

- export parent=$(pwd)

#
- >
  for path in \
    scala-gradle-maven-docker-starter \
    kotlin-gradle-maven-docker-starter \
    java-gradle-maven-docker-starter \
  ; do

    cd ${parent}/${path}

    bash mvnw
    bash gradlew
    docker-compose build --force-rm --no-cache --pull
    docker-compose up --force-recreate --remove-orphans
    docker-compose down -v
  done;

- docker system prune -af --volumes

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
