env:
  global:
    - TERM=dumb
    - secure: rbv5UwJyAECUi3AYqfzcmX0aXvzWjyuBtyDmvfRnNm2bDyal5dy16hxOiTPSNv0lsZ/2s7oiRxx9z8dcXf2p/Ff4VGFJvRpgFaqAa1ual93kyF0JED4hGoheEuTKEHnqYJcZRIqGgJioPkXlx2Oj0oUuaK9ncbl2SjLKHtvhbf6spBwp4CS7/65l6Bvpo9mc+d9llb3pJ2YG2FEsy43bxrUwu3xv9qYnRyGUfTpmGyvHDse0qaulzhHyaY/qs4t6A19GGcG53CTK4fCirAHiZEkElpv5dCMZU+pZWloxsMPE3zgJWJE3u6GuWZz0jfDmcf7mUZgt+Ty6BKeQn+Ef48YKqLliCnZ6je/0P5R6Yrk3XYkxgsHNHq+0V/9g9Xkv5lC3LJHecgVz/hiTKsMAEfEmVMCVL4aLYfYgnzPn1HjxOvt4UY07uVl0Sl7ncU3Jez6zIpQDJz/+ms3LJx8VeTHbnE4cn4Aft+LbQR5Z5JjKOCcCz+e+nx8nHumHUcpLnZWDl+pDdI9r4dN870sFdJMVeI+g9uoSbMpW5zN6TIAZBY3FyIeCbZI2Xh95ZyGi5xkXJ+G2bqYbnTgADE88Ej7pDzklmfH5vUzNfjY8b1F620i7xI1AmzwEWBGuJw9yu9AUdGcDSnLkAH5pg0VnoT4vb6y3Oa9C2msqCkoqiZw=
notifications:
  email: false
git:
  quiet: true
  depth: false
language: java
jdk: openjdk8
python: 3.7
os: linux
arch: amd64
install: true
services: docker
addons:
  apt:
    update: true
    packages:
      - curl
      - python3-pip
      - libhsdis0-fcml
      - docker-ce
before_install:
  - export PATH=$HOME/.local/bin:$PATH
  - pip3 install --user --upgrade pip setuptools
  - pip  install --user --upgrade docker-compose httpie
  - docker-compose version
  - |
    if [ ! -f ${HOME}/.local/daggerok/bash-functions/master/main.bash ] ; then
      mkdir -p ${HOME}/.local/daggerok/bash-functions/master
      curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash > ${HOME}/.local/daggerok/bash-functions/master/main.bash
    fi
    source ~/.local/daggerok/bash-functions/master/main.bash
  - stop_any 80 1234 8080 5432
  # scala-rsocket:
  - ulimit -c unlimited
  # https://github.com/sormuras/bach#install-jdksh
  # https://docs.travis-ci.com/user/languages/java/
  - export parent=$(pwd)
stages:
  - test
  - deploy
jobs:
  include:
#    - stage: test
#      #jdk: openjdk-ea
#      jdk: openjdk12
#      name: hello-world openjdk-ea
#      script:
#        - cd ${parent}/hello-world
#        - ./mvnw clean package
#        - java -jar ./target/*-all.jar
#        - ./gradlew clean build fatJar
#        - java -jar ./build/libs/*-all.jar
    - stage: test
      jdk: openjdk11
      name: an-akka-test openjdk11
      script:
        - cd $TRAVIS_BUILD_DIR/an-akka-test && java -version
        - cd $TRAVIS_BUILD_DIR/an-akka-test && ./sbtw clean assembly run
        - java -jar $TRAVIS_BUILD_DIR/an-akka-test/target/scala-*/*-assembly-*.jar
        - cd $TRAVIS_BUILD_DIR/an-akka-test && ./sbtw updateClassifiers
        - cd $TRAVIS_BUILD_DIR/an-akka-test && ./sbtw clean test
    - stage: test
      jdk: openjdk11
      name: a-config-akka-example openjdk11
      script:
        - cd $TRAVIS_BUILD_DIR/a-config-akka-example && java -version
        - cd $TRAVIS_BUILD_DIR/a-config-akka-example && ./sbtw clean test
        - cd $TRAVIS_BUILD_DIR/a-config-akka-example && ./sbtw run
        - cd $TRAVIS_BUILD_DIR/a-config-akka-example && ./sbtw clean assembly
        - java -jar $TRAVIS_BUILD_DIR/a-config-akka-example/target/scala-*/*-assembly-*.jar
    - stage: test
      jdk: openjdk12
      name: a-distributed-word-counter-example openjdk12
      script:
        - cd $TRAVIS_BUILD_DIR/a-distributed-word-counter-example && java -version
        - cd $TRAVIS_BUILD_DIR/a-distributed-word-counter-example && ./sbtw clean test
        - cd $TRAVIS_BUILD_DIR/a-distributed-word-counter-example && ./sbtw run
        - cd $TRAVIS_BUILD_DIR/a-distributed-word-counter-example && ./sbtw clean assembly
        - java -jar $TRAVIS_BUILD_DIR/a-distributed-word-counter-example/target/scala-*/*-assembly-*.jar
    - stage: test
      jdk: openjdk11
      name: an-actor-selection-example openjdk11
      script:
        - cd $TRAVIS_BUILD_DIR/an-actor-selection-example && java -version
        - cd $TRAVIS_BUILD_DIR/an-actor-selection-example && ./sbtw clean test
        - cd $TRAVIS_BUILD_DIR/an-actor-selection-example && ./sbtw run
        - cd $TRAVIS_BUILD_DIR/an-actor-selection-example && ./sbtw clean assembly
        - java -jar $TRAVIS_BUILD_DIR/an-actor-selection-example/target/scala-*/*-assembly-*.jar
    - stage: test
      jdk: openjdk11
      name: a-child-actor-example openjdk11
      script:
        - cd $TRAVIS_BUILD_DIR/a-child-actor-example && ./sbtw clean test
        - cd $TRAVIS_BUILD_DIR/a-child-actor-example && ./sbtw run
        - cd $TRAVIS_BUILD_DIR/a-child-actor-example && ./sbtw clean assembly
        - java -jar $TRAVIS_BUILD_DIR/a-child-actor-example/target/scala-*/*-assembly-*.jar
    - stage: test
      jdk: openjdk11
      name: a-bank-account-example openjdk11
      script:
        - cd $TRAVIS_BUILD_DIR/a-bank-account-example && ./sbtw clean test
        - cd $TRAVIS_BUILD_DIR/a-bank-account-example && ./sbtw run
        - cd $TRAVIS_BUILD_DIR/a-bank-account-example && ./sbtw clean assembly
        - java -jar $TRAVIS_BUILD_DIR/a-bank-account-example/target/scala-*/*-assembly-*.jar
    - stage: test
      jdk: openjdk11
      name: a-counter-example openjdk11
      script:
        - cd $TRAVIS_BUILD_DIR/a-counter-example && ./sbtw clean test
        - cd $TRAVIS_BUILD_DIR/a-counter-example && ./sbtw run
        - cd $TRAVIS_BUILD_DIR/a-counter-example && ./sbtw clean assembly
        - java -jar $TRAVIS_BUILD_DIR/a-counter-example/target/scala-*/*-assembly-*.jar
#    - stage: test
#      jdk: openjdk8
#      name: a-self-example openjdk8
#      script:
#        - cd $TRAVIS_BUILD_DIR/a-self-example && ./sbtw clean test
#        - cd $TRAVIS_BUILD_DIR/a-self-example && ./sbtw run
#        - cd $TRAVIS_BUILD_DIR/a-self-example && ./sbtw clean assembly
#        - java -jar $TRAVIS_BUILD_DIR/a-self-example/target/scala-*/*-assembly-*.jar
    - stage: test
      jdk: openjdk11
      name: a-self-example openjdk11
      script:
        - cd $TRAVIS_BUILD_DIR/a-self-example && ./sbtw clean test
        - cd $TRAVIS_BUILD_DIR/a-self-example && ./sbtw run
        - cd $TRAVIS_BUILD_DIR/a-self-example && ./sbtw clean assembly
        - java -jar $TRAVIS_BUILD_DIR/a-self-example/target/scala-*/*-assembly-*.jar
#    - stage: test
#      jdk: openjdk8
#      name: a-logger-example openjdk8
#      script:
#        - cd $TRAVIS_BUILD_DIR/a-logger-example && ./sbtw clean test
#        - cd $TRAVIS_BUILD_DIR/a-logger-example && ./sbtw run
#        - cd $TRAVIS_BUILD_DIR/a-logger-example && ./sbtw clean assembly
#        - java -jar $TRAVIS_BUILD_DIR/a-logger-example/target/scala-*/*-assembly-*.jar
    - stage: test
      jdk: openjdk11
      name: a-logger-example openjdk11
      script:
        - cd $TRAVIS_BUILD_DIR/a-logger-example && ./sbtw clean test
        - cd $TRAVIS_BUILD_DIR/a-logger-example && ./sbtw run
        - cd $TRAVIS_BUILD_DIR/a-logger-example && ./sbtw clean assembly
        - java -jar $TRAVIS_BUILD_DIR/a-logger-example/target/scala-*/*-assembly-*.jar
#    - stage: test
#      jdk: openjdk8
#      name: a-ping-pong-example openjdk8
#      script:
#        - cd $TRAVIS_BUILD_DIR/a-ping-pong-example && ./sbtw clean test
#        - cd $TRAVIS_BUILD_DIR/a-ping-pong-example && ./sbtw run
#        - cd $TRAVIS_BUILD_DIR/a-ping-pong-example && ./sbtw clean assembly
#        - java -jar $TRAVIS_BUILD_DIR/a-ping-pong-example/target/scala-*/*-assembly-*.jar
    - stage: test
      jdk: openjdk11
      name: a-ping-pong-example openjdk11
      script:
        - cd $TRAVIS_BUILD_DIR/a-ping-pong-example && ./sbtw clean test
        - cd $TRAVIS_BUILD_DIR/a-ping-pong-example && ./sbtw run
        - cd $TRAVIS_BUILD_DIR/a-ping-pong-example && ./sbtw clean assembly
        - java -jar $TRAVIS_BUILD_DIR/a-ping-pong-example/target/scala-*/*-assembly-*.jar
#    - stage: test
#      jdk: openjdk8
#      name: a-simple-example openjdk8
#      script:
#        - cd $TRAVIS_BUILD_DIR/a-simple-example && ./sbtw clean test
#        - cd $TRAVIS_BUILD_DIR/a-simple-example && ./sbtw run
#        - cd $TRAVIS_BUILD_DIR/a-simple-example && ./sbtw clean assembly
#        - java -jar $TRAVIS_BUILD_DIR/a-simple-example/target/scala-*/*-assembly-*.jar
    - stage: test
      jdk: openjdk11
      name: a-simple-example openjdk11
      script:
        - cd $TRAVIS_BUILD_DIR/a-simple-example && ./sbtw clean test
        - cd $TRAVIS_BUILD_DIR/a-simple-example && ./sbtw run
        - cd $TRAVIS_BUILD_DIR/a-simple-example && ./sbtw clean assembly
        - java -jar $TRAVIS_BUILD_DIR/a-simple-example/target/scala-*/*-assembly-*.jar
    - stage: test
      jdk: openjdk11
      name: idea-scala-sbt-project openjdk11
      script:
        ## jdk 8
        ##- jdk_switcher use oraclejdk8
        #- jdk_switcher use openjdk8
        - cd ${parent}/idea-scala-sbt-project
        - ./sbtw clean compile test assembly
        - java -jar target/scala-*/*-assembly-*.jar
#    - stage: test
#      jdk: openjdk8
#      name: idea-scala-sbt-project openjdk8
#      script:
#        ## jdk 8
#        ##- jdk_switcher use oraclejdk8
#        #- jdk_switcher use openjdk8
#        - cd ${parent}/idea-scala-sbt-project
#        - ./sbtw clean compile test assembly
#        - java -jar target/scala-*/*-assembly-*.jar
    - stage: test
      jdk: openjdk8
      name: another-akka-try openjdk8
      script:
        - cd ${parent}/another-akka-try
        - bash ./gradlew clean installDist >/dev/null
        - bash ./build/install/another-akka-try/bin/another-akka-try
        - bash ./mvnw clean package com.dkanejs.maven.plugins:docker-compose-maven-plugin:1.0.1:up
        - bash ./mvnw com.dkanejs.maven.plugins:docker-compose-maven-plugin:1.0.1:down
    - stage: test
      jdk: openjdk8
      name: scala-gradle-maven-docker-starter openjdk8
      script:
        - cd ${parent}/scala-gradle-maven-docker-starter ;
        - bash mvnw >/dev/null ;
        - bash gradlew >/dev/null ;
        - docker-compose build --force-rm --no-cache --pull ;
        - docker-compose up --force-recreate --remove-orphans ;
        - docker-compose down -v ;
        #- docker system prune -af --volumes
    - stage: test
      jdk: openjdk8
      name: kotlin-gradle-maven-docker-starter openjdk8
      script:
        - cd ${parent}/kotlin-gradle-maven-docker-starter
        - bash mvnw >/dev/null
        - bash gradlew >/dev/null
        - docker-compose build --force-rm --no-cache --pull
        - docker-compose up --force-recreate --remove-orphans
        - docker-compose down -v
    - stage: test
      jdk: openjdk8
      name: java-gradle-maven-docker-starter openjdk8
      script:
        - cd ${parent}/java-gradle-maven-docker-starter
        - bash mvnw >/dev/null
        - bash gradlew >/dev/null
        - docker-compose build --force-rm --no-cache --pull
        - docker-compose up --force-recreate --remove-orphans
        - docker-compose down -v
before_cache:
  - bash -c 'for item in $(find ~/.gradle -name "*.lock") ; do sudo rm -rfv $item ; done'
cache:
  pip: true
  packages: true
  directories:
    - $HOME/.m2
    - $HOME/.sbt
    - $HOME/.ivy
    - $HOME/.gradle
    - $HOME/.docker
    - $HOME/openjdk*
    - $HOME/.local/daggerok
