version: "2.1"

services:

  java-gradle-starter:
    build:
      context: .
      dockerfile: ./docker/gradle/Dockerfile
    volumes: ["java-gradle-starter-data:/home/appuser"]
#    ports:
#      - "5005:5005"
#      - "8080:8080"
#    restart: unless-stopped
    networks: [backing-services]

  java-maven-starter:
    build:
      context: .
      dockerfile: ./docker/maven/Dockerfile
    volumes: ["java-maven-starter-data:/home/appuser"]
#    ports:
#      - "5006:5005"
#      - "8081:8080"
#    restart: unless-stopped
    networks: [backing-services]

volumes:
  java-gradle-starter-data: {}
  java-maven-starter-data: {}

networks:
  backing-services:
    driver: bridge
