# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
name: 'GitHub actions'
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      check-updates:
        description: 'Check Gradle versions updates'
        required: true
        default: '.'
jobs:
  dependency-updates:
    if: github.event.inputs.check-updates != '' # disable local deploy triggered automatically as not needed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: akka-examples-gradle
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-${{ hashFiles('**/build.gradle.kts') }}
      - uses: actions/cache@v2
        id: akka-examples-mvn
        with:
          path: |
            ~/.m2
            !~/.m2/repository/com/gituhb/daggerok
          key: ${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
      - uses: actions/cache@v2
        id: akka-examples-npm
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ hashFiles('**/package.json') }}
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: echo './gradlew dependencyUpdates -Drevision=release'
  rsocket-akka-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: akka-examples-gradle
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-${{ hashFiles('**/build.gradle.kts') }}
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: cd ./rsocket-akka-app ; ./gradlew clean build fatJar
      - run: java -jar ./rsocket-akka-app/build/libs/*-all.jar
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: akka-examples-mvn
        with:
          path: |
            ~/.m2
            !~/.m2/repository/com/gituhb/daggerok
          key: ${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
      - uses: actions/cache@v2
        id: akka-examples-npm
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ hashFiles('**/package.json') }}
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/setup-node@v2
      - run: ./mvnw
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: target/generated-docs # The folder the action should deploy.
